language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r pip-requirements --use-mirrors"
# command to run tests
script: nosetests
# run deploy script on server
notifications:
  webhooks: http://serve.webstandardsdays.ru/
